<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="prod.css">
    <title>Document</title>
</head>
<body>
<div class="general_container">
    <div class="container">

        <div class="img_container">
            <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/97/39/7f/caption.jpg?w=1200&h=-1&s=1&cx=1920&cy=1080&chk=v1_f31158e4bb953d28a308" alt="" id="img_container">
        </div>

        <div class="mark_container">
            <p>dasdsadsad</p>
        </div>

        <div class="name_container">
        <p>dasdsadsad</p>
        </div>

        <div class="price_container">
        <p>dasdsadsad</p>
        </div>

    </div>

    <div class="container">

        <div class="img_container">
            <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/97/39/7f/caption.jpg?w=1200&h=-1&s=1&cx=1920&cy=1080&chk=v1_f31158e4bb953d28a308" alt="" id="img_container">
        </div>

        <div class="mark_container">
            <p>dasdsadsad</p>
        </div>

        <div class="name_container">
        <p>dasdsadsad</p>
        </div>

        <div class="price_container">
        <p>dasdsadsad</p>
        </div>

    </div>

    <div class="container">

        <div class="img_container">
            <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/97/39/7f/caption.jpg?w=1200&h=-1&s=1&cx=1920&cy=1080&chk=v1_f31158e4bb953d28a308" alt="" id="img_container">
        </div>

        <div class="mark_container">
            <p>dasdsadsad</p>
        </div>

        <div class="name_container">
        <p>dasdsadsad</p>
        </div>

        <div class="price_container">
        <p>dasdsadsad</p>
        </div>

    </div>

    <div class="container">

        <div class="img_container">
            <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/97/39/7f/caption.jpg?w=1200&h=-1&s=1&cx=1920&cy=1080&chk=v1_f31158e4bb953d28a308" alt="" id="img_container">
        </div>

        <div class="mark_container">
            <p>dasdsadsad</p>
        </div>

        <div class="name_container">
        <p>dasdsadsad</p>
        </div>

        <div class="price_container">
        <p>dasdsadsad</p>
        </div>

    </div>
</div>

</body>
</html>